/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication14;

import java.awt.HeadlessException;
import java.util.HashSet;
import javax.swing.JDesktopPane;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Maxi Ybañez
 */
public class Menu extends javax.swing.JFrame {
    
    private static HashSet<Materia> materias= new HashSet<>();
    private static HashSet<Alumno> alumnos= new HashSet<>();

    public Menu(JDesktopPane Escritorio, JMenu jMenu1, JMenu jMenu2, JMenu jMenu5, JMenuBar jMenuBar1, JMenuItem jMenuItem1, JMenu jmAgregarAlumno, JMenu jmCerrar, JMenu jmInscribir, JMenu jmSalir) throws HeadlessException {
        this.Escritorio = Escritorio;
        this.jmSalir = jMenu1;
        this.jmAltaMaterias = jMenu2;
        
        this.jMenuBar1 = jMenuBar1;
        this.jMenuItem1 = jMenuItem1;
        
        this.jmSalir = jmSalir;
    }
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }
    public static HashSet getMaterias(){
        return materias;
    }
     public static HashSet<Alumno> getAlumnos(){
        return alumnos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        ImageIcon icono= new ImageIcon(getClass().getResource("/imagenes/logo.jpg"));
        Image imagen= icono.getImage();
        Escritorio = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(imagen,0,0,getWidth(),getHeight(),this);
            }
        }
        ;
        jMenuBar1 = new javax.swing.JMenuBar();
        jmSalir = new javax.swing.JMenu();
        jmAlumnosAlta = new javax.swing.JMenuItem();
        jmInscribirMaterias = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jmAltaMaterias = new javax.swing.JMenu();
        jmMateriaAlta = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Practico-N°7-seccion alumno");
        setLocation(new java.awt.Point(400, 150));

        Escritorio.setBackground(new java.awt.Color(255, 255, 255));

        Escritorio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Escritorio.setName("");

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 462, Short.MAX_VALUE)
        );

        jmSalir.setBackground(new java.awt.Color(0, 204, 204));
        jmSalir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jmSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-colegial-en-un-escritorio-24.png"))); // NOI18N
        jmSalir.setText("Seccion Alumno");
        jmSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmSalir.setFont(new java.awt.Font("Siemens TIA Portal Basic", 1, 12)); // NOI18N

        jmAlumnosAlta.setText("Alta de Alumnos");
        jmAlumnosAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAlumnosAltaActionPerformed(evt);
            }
        });
        jmSalir.add(jmAlumnosAlta);

        jmInscribirMaterias.setText("Inscribir a materias");
        jmInscribirMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmInscribirMateriasActionPerformed(evt);
            }
        });
        jmSalir.add(jmInscribirMaterias);

        jMenuItem5.setText("Exit");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jmSalir.add(jMenuItem5);

        jMenuBar1.add(jmSalir);

        jmAltaMaterias.setBackground(new java.awt.Color(0, 204, 204));
        jmAltaMaterias.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jmAltaMaterias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-casa-de-la-escuela-24.png"))); // NOI18N
        jmAltaMaterias.setText("Seccion Materias");
        jmAltaMaterias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmAltaMaterias.setFont(new java.awt.Font("Siemens TIA Portal Basic", 1, 12)); // NOI18N

        jmMateriaAlta.setText("Alta de Materias");
        jmMateriaAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmMateriaAltaActionPerformed(evt);
            }
        });
        jmAltaMaterias.add(jmMateriaAlta);

        jMenuBar1.add(jmAltaMaterias);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Escritorio)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmAlumnosAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAlumnosAltaActionPerformed
        // TODO add your handling code here:
          AgregarAlumno alum= new AgregarAlumno();
        alum.setVisible(true);
        Escritorio.add(alum);
    }//GEN-LAST:event_jmAlumnosAltaActionPerformed

    private void jmMateriaAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmMateriaAltaActionPerformed
        // TODO add your handling code here:
        AgregarMateria mat= new AgregarMateria();
        mat.setVisible(true);
        Escritorio.add(mat);
    }//GEN-LAST:event_jmMateriaAltaActionPerformed

    private void jmInscribirMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmInscribirMateriasActionPerformed
        // TODO add your handling code here:
         
        InscripcionMateria mat= new InscripcionMateria();
        mat.setVisible(true);
        Escritorio.add(mat);
    }//GEN-LAST:event_jmInscribirMateriasActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenu jmAltaMaterias;
    private javax.swing.JMenuItem jmAlumnosAlta;
    private javax.swing.JMenuItem jmInscribirMaterias;
    private javax.swing.JMenuItem jmMateriaAlta;
    private javax.swing.JMenu jmSalir;
    // End of variables declaration//GEN-END:variables
}
